### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by luisdavim** [dex4er/asdf-helm-diff#1]
Hi, it looks like the artefact names have changed:

```
asdf install helm-diff latest
Downloading helm-diff from https://github.com/databus23/helm-diff/releases/download/v3.3.2/helm-diff-macos.tgz
gzip: unknown compression format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by khassel** [comment]
yes, since `v3.3.0` the url has changed from

`https://github.com/databus23/helm-diff/releases/download/v3.3.2/helm-diff-linux.tgz`

to

`https://github.com/databus23/helm-diff/releases/download/v3.3.2/helm-diff-linux-amd64.tgz`
