### ISSUE TITLE
What is the difference between this repo and https://github.com/istreamlabs/asdf-helm-diff/tree/master/bin?

### ISSUE THREAD

**Issue by lmilbaum** [dex4er/asdf-helm-diff#4]
Which one should I pick if I want it to be supported by Renovate?

**Comment by dex4er** [comment]
I think you can check which one works for you. I see that `istreamlabs` version uses just `helm plugin` commands to install it and my version acts like all standard asdf plugins then it download the binary directly with `curl`.
